image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "27"
  ANDROID_BUILD_TOOLS: "27.0.1"
  ANDROID_SDK_TOOLS:   "4333796"

before_script:
  - wget -q -O android-sdk.zip "https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip"
  - unzip -q -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/platform-tools/
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses >/dev/null || true
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=$PWD/.gradle
  - export GRADLE_OPTS="-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle/wrapper/
    - .gradle/caches/

stages:
  - build
  - test

assemble:
  stage: build
  script:
    - ./gradlew assemble -x signProductionPlayRelease -x signProductionWebsiteRelease
  artifacts:
    paths:
      - build/outputs/

test:
  stage: test
  script:
    - ./gradlew -Pci --console=plain test
